"""initial foundation: users, processing_runs, ai_invocations, workflow_events

Revision ID: 410ab56e9209
Revises: 
Create Date: 2026-09-04 13:12:59.633703

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '410ab56e9209'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processing_runs',
    sa.Column('trigger', sa.Enum('CRON', 'MANUAL', name='processing_run_trigger'), nullable=False),
    sa.Column('job_type', sa.Enum('INGEST', 'ANALYZE', 'AGGREGATE', 'TREND', 'SUMMARY', name='processing_run_job_type'), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'COMPLETED_WITH_ERRORS', 'FAILED', name='processing_run_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviews_in_scope', sa.Integer(), nullable=False),
    sa.Column('reviews_succeeded', sa.Integer(), nullable=False),
    sa.Column('reviews_failed', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('workflow_events',
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('from_state', sa.String(length=64), nullable=True),
    sa.Column('to_state', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_events_entity_id'), 'workflow_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_workflow_events_entity_type'), 'workflow_events', ['entity_type'], unique=False)
    op.create_table('ai_invocations',
    sa.Column('processing_run_id', sa.Uuid(), nullable=True),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_estimate_usd', sa.Float(), nullable=True),
    sa.Column('validation_passed', sa.Boolean(), nullable=False),
    sa.Column('error_type', sa.String(length=64), nullable=True),
    sa.Column('input_ref', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['processing_run_id'], ['processing_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_invocations_processing_run_id'), 'ai_invocations', ['processing_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_invocations_processing_run_id'), table_name='ai_invocations')
    op.drop_table('ai_invocations')
    op.drop_index(op.f('ix_workflow_events_entity_type'), table_name='workflow_events')
    op.drop_index(op.f('ix_workflow_events_entity_id'), table_name='workflow_events')
    op.drop_table('workflow_events')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('processing_runs')
    # ### end Alembic commands ###
