"""insights table and grounded insight generation

Revision ID: 77ea17399fcb
Revises: 9d0847791b77
Create Date: 2026-09-07 14:06:35.120242

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '77ea17399fcb'
down_revision: str | None = '9d0847791b77'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Not autogenerated (same as ISSUE_DETECTION in an earlier migration): Alembic's
    # autogenerate doesn't detect new values added to an existing Postgres native enum.
    # Existing labels are uppercase (INGEST/ANALYZE/.../ISSUE_DETECTION), so this must
    # match that convention.
    op.execute("ALTER TYPE processing_run_job_type ADD VALUE IF NOT EXISTS 'INSIGHT'")


def downgrade() -> None:
    # Postgres has no simple "remove enum value" operation; left in place (harmless).
    pass
