"""outcome tracking: outcomes table

Revision ID: 7d59544f6ae9
Revises: b022014ee192
Create Date: 2026-09-07 14:42:09.330619

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7d59544f6ae9'
down_revision: str | None = 'b022014ee192'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Not autogenerated (same pattern as ISSUE_DETECTION/INSIGHT before): Alembic's
    # autogenerate doesn't detect new values added to an existing Postgres native enum.
    # Existing labels are uppercase, so this must match that convention.
    op.execute("ALTER TYPE processing_run_job_type ADD VALUE IF NOT EXISTS 'OUTCOME'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outcomes',
    sa.Column('action_id', sa.Uuid(), nullable=False),
    sa.Column('before_period_start', sa.Date(), nullable=False),
    sa.Column('before_period_end', sa.Date(), nullable=False),
    sa.Column('before_negative_count', sa.Integer(), nullable=False),
    sa.Column('after_period_start', sa.Date(), nullable=True),
    sa.Column('after_period_end', sa.Date(), nullable=True),
    sa.Column('after_negative_count', sa.Integer(), nullable=True),
    sa.Column('delta_pct', sa.Float(), nullable=True),
    sa.Column('interpretation', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action_id', name='uq_outcome_action_id')
    )
    op.create_index(op.f('ix_outcomes_action_id'), 'outcomes', ['action_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outcomes_action_id'), table_name='outcomes')
    op.drop_table('outcomes')
    # ### end Alembic commands ###
