"""aggregation and recurring-issue detection: aggregate_period_metrics, issues, issue_evidence

Revision ID: 99441b0d84c1
Revises: f0530f095ecf
Create Date: 2026-09-07 13:04:29.596978

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '99441b0d84c1'
down_revision: str | None = 'f0530f095ecf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Not autogenerated: Alembic's autogenerate doesn't detect new values added to an
    # existing Postgres native enum type. Safe to run inside this transaction on
    # Postgres 12+ as long as the new value isn't used until a later transaction.
    #
    # SQLAlchemy's Enum(PyEnumClass) stores the member NAME by default (not .value) —
    # existing labels here are INGEST/ANALYZE/AGGREGATE/TREND/SUMMARY, so the new one
    # must match that convention (ISSUE_DETECTION), not the lowercase Python value.
    op.execute("ALTER TYPE processing_run_job_type ADD VALUE IF NOT EXISTS 'ISSUE_DETECTION'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aggregate_period_metrics',
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('aspect_id', sa.Uuid(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.Column('negative_count', sa.Integer(), nullable=False),
    sa.Column('positive_count', sa.Integer(), nullable=False),
    sa.Column('neutral_count', sa.Integer(), nullable=False),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aspect_id'], ['aspects.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'location_id', 'topic_id', 'aspect_id', 'period_start', name='uq_apm_scope_period')
    )
    op.create_index(op.f('ix_aggregate_period_metrics_aspect_id'), 'aggregate_period_metrics', ['aspect_id'], unique=False)
    op.create_index(op.f('ix_aggregate_period_metrics_business_id'), 'aggregate_period_metrics', ['business_id'], unique=False)
    op.create_index(op.f('ix_aggregate_period_metrics_location_id'), 'aggregate_period_metrics', ['location_id'], unique=False)
    op.create_index(op.f('ix_aggregate_period_metrics_period_start'), 'aggregate_period_metrics', ['period_start'], unique=False)
    op.create_index(op.f('ix_aggregate_period_metrics_topic_id'), 'aggregate_period_metrics', ['topic_id'], unique=False)
    op.create_index('uq_apm_scope_period_business_wide', 'aggregate_period_metrics', ['business_id', 'topic_id', 'aspect_id', 'period_start'], unique=True, postgresql_where=sa.text('location_id IS NULL'))
    op.create_table('issues',
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('aspect_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('priority_score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('first_detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['aspect_id'], ['aspects.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issues_aspect_id'), 'issues', ['aspect_id'], unique=False)
    op.create_index(op.f('ix_issues_business_id'), 'issues', ['business_id'], unique=False)
    op.create_index(op.f('ix_issues_location_id'), 'issues', ['location_id'], unique=False)
    op.create_index(op.f('ix_issues_topic_id'), 'issues', ['topic_id'], unique=False)
    op.create_table('issue_evidence',
    sa.Column('issue_id', sa.Uuid(), nullable=False),
    sa.Column('aggregate_period_metric_id', sa.Uuid(), nullable=True),
    sa.Column('review_id', sa.Uuid(), nullable=True),
    sa.Column('evidence_type', sa.String(length=32), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['aggregate_period_metric_id'], ['aggregate_period_metrics.id'], ),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issue_evidence_aggregate_period_metric_id'), 'issue_evidence', ['aggregate_period_metric_id'], unique=False)
    op.create_index(op.f('ix_issue_evidence_issue_id'), 'issue_evidence', ['issue_id'], unique=False)
    op.create_index(op.f('ix_issue_evidence_review_id'), 'issue_evidence', ['review_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Postgres has no simple "remove enum value" operation; the 'issue_detection' value
    # added in upgrade() is intentionally left in place on downgrade (harmless if unused).
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issue_evidence_review_id'), table_name='issue_evidence')
    op.drop_index(op.f('ix_issue_evidence_issue_id'), table_name='issue_evidence')
    op.drop_index(op.f('ix_issue_evidence_aggregate_period_metric_id'), table_name='issue_evidence')
    op.drop_table('issue_evidence')
    op.drop_index(op.f('ix_issues_topic_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_location_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_business_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_aspect_id'), table_name='issues')
    op.drop_table('issues')
    op.drop_index('uq_apm_scope_period_business_wide', table_name='aggregate_period_metrics', postgresql_where=sa.text('location_id IS NULL'))
    op.drop_index(op.f('ix_aggregate_period_metrics_topic_id'), table_name='aggregate_period_metrics')
    op.drop_index(op.f('ix_aggregate_period_metrics_period_start'), table_name='aggregate_period_metrics')
    op.drop_index(op.f('ix_aggregate_period_metrics_location_id'), table_name='aggregate_period_metrics')
    op.drop_index(op.f('ix_aggregate_period_metrics_business_id'), table_name='aggregate_period_metrics')
    op.drop_index(op.f('ix_aggregate_period_metrics_aspect_id'), table_name='aggregate_period_metrics')
    op.drop_table('aggregate_period_metrics')
    # ### end Alembic commands ###
