"""trend/priority fields on issues, insights table

Revision ID: 9d0847791b77
Revises: 99441b0d84c1
Create Date: 2026-09-07 14:00:12.503118

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9d0847791b77'
down_revision: str | None = '99441b0d84c1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insights',
    sa.Column('issue_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.String(length=1000), nullable=False),
    sa.Column('generation_method', sa.String(length=32), nullable=False),
    sa.Column('ai_invocation_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ai_invocation_id'], ['ai_invocations.id'], ),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insights_issue_id'), 'insights', ['issue_id'], unique=False)
    op.add_column('issues', sa.Column('trend_direction', sa.String(length=32), nullable=True))
    op.add_column('issues', sa.Column('trend_change_pct', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'trend_change_pct')
    op.drop_column('issues', 'trend_direction')
    op.drop_index(op.f('ix_insights_issue_id'), table_name='insights')
    op.drop_table('insights')
    # ### end Alembic commands ###
