"""actions, action approvals, and human approval workflow

Revision ID: b022014ee192
Revises: 77ea17399fcb
Create Date: 2026-09-07 14:23:01.980238

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b022014ee192'
down_revision: str | None = '77ea17399fcb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('issue_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('recommended_text', sa.String(length=1000), nullable=False),
    sa.Column('ai_invocation_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ai_invocation_id'], ['ai_invocations.id'], ),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actions_issue_id'), 'actions', ['issue_id'], unique=False)
    op.create_table('action_approvals',
    sa.Column('action_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('approver', sa.String(length=255), nullable=False),
    sa.Column('decision_note', sa.String(length=1000), nullable=True),
    sa.Column('modified_text', sa.String(length=1000), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_approvals_action_id'), 'action_approvals', ['action_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_approvals_action_id'), table_name='action_approvals')
    op.drop_table('action_approvals')
    op.drop_index(op.f('ix_actions_issue_id'), table_name='actions')
    op.drop_table('actions')
    # ### end Alembic commands ###
