"""domain model: business, location, taxonomy, review

Revision ID: ec372ab80cf9
Revises: 410ab56e9209
Create Date: 2026-09-04 13:35:24.784635

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ec372ab80cf9'
down_revision: str | None = '410ab56e9209'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('topics',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('aspects',
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'key', name='uq_aspect_topic_key')
    )
    op.create_index(op.f('ix_aspects_topic_id'), 'aspects', ['topic_id'], unique=False)
    op.create_table('locations',
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('opened_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'name', name='uq_location_business_name')
    )
    op.create_index(op.f('ix_locations_business_id'), 'locations', ['business_id'], unique=False)
    op.create_table('reviews',
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('source_review_id', sa.String(length=128), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=5000), nullable=False),
    sa.Column('detected_language', sa.String(length=8), nullable=True),
    sa.Column('reviewer_display_name', sa.String(length=255), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingestion_status', sa.String(length=16), nullable=False),
    sa.Column('analysis_status', sa.String(length=16), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('rating IS NULL OR (rating >= 1 AND rating <= 5)', name='ck_review_rating_range'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'source', 'source_review_id', name='uq_review_business_source_id')
    )
    op.create_index(op.f('ix_reviews_business_id'), 'reviews', ['business_id'], unique=False)
    op.create_index(op.f('ix_reviews_location_id'), 'reviews', ['location_id'], unique=False)
    op.create_index('uq_review_business_location_hash_no_source_id', 'reviews', ['business_id', 'location_id', 'content_hash'], unique=True, postgresql_where=sa.text('source_review_id IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_review_business_location_hash_no_source_id', table_name='reviews', postgresql_where=sa.text('source_review_id IS NULL'))
    op.drop_index(op.f('ix_reviews_location_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_business_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_locations_business_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_aspects_topic_id'), table_name='aspects')
    op.drop_table('aspects')
    op.drop_table('topics')
    op.drop_table('businesses')
    # ### end Alembic commands ###
