"""ai analysis: review_analyses, review_aspects

Revision ID: f0530f095ecf
Revises: ec372ab80cf9
Create Date: 2026-09-05 14:13:58.353654

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f0530f095ecf'
down_revision: str | None = 'ec372ab80cf9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_analyses',
    sa.Column('review_id', sa.Uuid(), nullable=False),
    sa.Column('ai_invocation_id', sa.Uuid(), nullable=False),
    sa.Column('overall_sentiment', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ai_invocation_id'], ['ai_invocations.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id', name='uq_review_analysis_review_id')
    )
    op.create_index(op.f('ix_review_analyses_review_id'), 'review_analyses', ['review_id'], unique=False)
    op.create_table('review_aspects',
    sa.Column('review_analysis_id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('aspect_id', sa.Uuid(), nullable=False),
    sa.Column('aspect_sentiment', sa.String(length=16), nullable=False),
    sa.Column('evidence_snippet', sa.String(length=500), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['aspect_id'], ['aspects.id'], ),
    sa.ForeignKeyConstraint(['review_analysis_id'], ['review_analyses.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_aspects_aspect_id'), 'review_aspects', ['aspect_id'], unique=False)
    op.create_index(op.f('ix_review_aspects_review_analysis_id'), 'review_aspects', ['review_analysis_id'], unique=False)
    op.create_index(op.f('ix_review_aspects_topic_id'), 'review_aspects', ['topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_aspects_topic_id'), table_name='review_aspects')
    op.drop_index(op.f('ix_review_aspects_review_analysis_id'), table_name='review_aspects')
    op.drop_index(op.f('ix_review_aspects_aspect_id'), table_name='review_aspects')
    op.drop_table('review_aspects')
    op.drop_index(op.f('ix_review_analyses_review_id'), table_name='review_analyses')
    op.drop_table('review_analyses')
    # ### end Alembic commands ###
